kind: Service
apiVersion: v1
metadata:
  name: xcache-network
  namespace: xcache
  annotations:
    external-dns.alpha.kubernetes.io/hostname: atlas.xcache.org
  labels:
    k8s-app: xcache-network
spec:
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: xcache-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcache-network  
  namespace: xcache
  labels:
    k8s-app: xcache-network
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: xcache-network
  template:
    metadata:
      labels:
        k8s-app: xcache-network
    spec:
      containers:
      - name: xcache-network
        image: slateci/xcache-network:latest
        ports:
          - containerPort: 443
          - containerPort: 80
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 443
          periodSeconds: 60
          initialDelaySeconds: 600000
          timeoutSeconds: 10
        volumeMounts:
        - name: https-certs-volume
          mountPath: "/etc/https-certs/"
          readOnly: true
        - name: conf-volume
          mountPath: "/etc/backend-conf/"
      volumes:
      - name: https-certs-volume
        secret:
          secretName: cert-secret
          items:
          - key: key
            path: key.pem
            mode: 256 
          - key: cert
            path: cert.pem
      - name: conf-volume
        secret:
          secretName: config
          items:
          - key: config
            path: config.json
